# Generated by Django 2.2.10 on 2021-12-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211221_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
